language: cpp
sudo: false
compiler:
   - g++
branches:
  only:
  - master
before_install:
  - sudo apt-get update
install: 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
befor_script:
script: 
  - cmake -DHIREDIS_PATH=../hiredis/ -DCMAKE_BUILD_TYPE=Debug . 
  - export CXX="g++-4.8"
  - make