language: cpp
sudo: required
compiler:
   - gcc
branches:
  only:
  - master
before_install:
#   - sudo apt-get update
notifications:
  recipients:
    - wongya@gmail.com
  email:
#    on_success: change
#    on_failure: always
befor_script:
  - cmake -DHIREDIS_PATH=../hiredis/ -DCMAKE_BUILD_TYPE=Debug .
script: make