language: cpp
sudo: required
compiler:
   - g++
branches:
  only:
  - master
before_install:
  - sudo apt-get update
install: 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
befor_script:
script: 
  - export CXX=g++-4.9
  - cmake -DHIREDIS_PATH=./lib/hiredis/ -DCMAKE_BUILD_TYPE=Debug . 
  - make
  
notifications:
  recipients:
    - wongya@gmail.com
  email:
#    on_success: change
#    on_failure: always